// flow-typed signature: b48c573ccacb0f46873650b3b6b199e7
// flow-typed version: <<STUB>>/babel-plugin-react-intl_v^4.1.12/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-intl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-intl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-intl/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-react-intl/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/dist/index'>;
}
