// flow-typed signature: 233dc3b1697a62d8b4cb3b69caef2629
// flow-typed version: <<STUB>>/is-wsl_v^1.1.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-wsl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-wsl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-wsl/index' {
  declare module.exports: $Exports<'is-wsl'>;
}
declare module 'is-wsl/index.js' {
  declare module.exports: $Exports<'is-wsl'>;
}
