// flow-typed signature: 044e498f5cd13d5c446224a197849054
// flow-typed version: <<STUB>>/jest-resolve_v24.8.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-resolve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-resolve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-resolve/build/defaultResolver' {
  declare module.exports: any;
}

declare module 'jest-resolve/build/index' {
  declare module.exports: any;
}

declare module 'jest-resolve/build/isBuiltinModule' {
  declare module.exports: any;
}

declare module 'jest-resolve/build/nodeModulesPaths' {
  declare module.exports: any;
}

declare module 'jest-resolve/build/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-resolve/build/defaultResolver.js' {
  declare module.exports: $Exports<'jest-resolve/build/defaultResolver'>;
}
declare module 'jest-resolve/build/index.js' {
  declare module.exports: $Exports<'jest-resolve/build/index'>;
}
declare module 'jest-resolve/build/isBuiltinModule.js' {
  declare module.exports: $Exports<'jest-resolve/build/isBuiltinModule'>;
}
declare module 'jest-resolve/build/nodeModulesPaths.js' {
  declare module.exports: $Exports<'jest-resolve/build/nodeModulesPaths'>;
}
declare module 'jest-resolve/build/types.js' {
  declare module.exports: $Exports<'jest-resolve/build/types'>;
}
