// flow-typed signature: 80189c310114cb421dd4a0d5ab6c2fd9
// flow-typed version: <<STUB>>/pnp-webpack-plugin_v1.5.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pnp-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pnp-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pnp-webpack-plugin/fixtures/file' {
  declare module.exports: any;
}

declare module 'pnp-webpack-plugin/fixtures/index' {
  declare module.exports: any;
}

declare module 'pnp-webpack-plugin/index.test' {
  declare module.exports: any;
}

declare module 'pnp-webpack-plugin/jest.config' {
  declare module.exports: any;
}

declare module 'pnp-webpack-plugin/ts' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pnp-webpack-plugin/fixtures/file.js' {
  declare module.exports: $Exports<'pnp-webpack-plugin/fixtures/file'>;
}
declare module 'pnp-webpack-plugin/fixtures/index.js' {
  declare module.exports: $Exports<'pnp-webpack-plugin/fixtures/index'>;
}
declare module 'pnp-webpack-plugin/index' {
  declare module.exports: $Exports<'pnp-webpack-plugin'>;
}
declare module 'pnp-webpack-plugin/index.js' {
  declare module.exports: $Exports<'pnp-webpack-plugin'>;
}
declare module 'pnp-webpack-plugin/index.test.js' {
  declare module.exports: $Exports<'pnp-webpack-plugin/index.test'>;
}
declare module 'pnp-webpack-plugin/jest.config.js' {
  declare module.exports: $Exports<'pnp-webpack-plugin/jest.config'>;
}
declare module 'pnp-webpack-plugin/ts.js' {
  declare module.exports: $Exports<'pnp-webpack-plugin/ts'>;
}
