// flow-typed signature: f5b2116fbaf7322d3012dbba7f6e171f
// flow-typed version: <<STUB>>/postcss-safe-parser_v4.0.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-safe-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-safe-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-safe-parser/lib/safe-parse' {
  declare module.exports: any;
}

declare module 'postcss-safe-parser/lib/safe-parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-safe-parser/lib/safe-parse.js' {
  declare module.exports: $Exports<'postcss-safe-parser/lib/safe-parse'>;
}
declare module 'postcss-safe-parser/lib/safe-parser.js' {
  declare module.exports: $Exports<'postcss-safe-parser/lib/safe-parser'>;
}
