// flow-typed signature: 429f975769839651e2675f91d52cf5a6
// flow-typed version: <<STUB>>/sendbird_v^3.0.104/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sendbird'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sendbird' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sendbird/SendBird.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sendbird/SendBird.min.js' {
  declare module.exports: $Exports<'sendbird/SendBird.min'>;
}
