// flow-typed signature: 738a224434623e86ed7738bbbd503e3e
// flow-typed version: <<STUB>>/ts-pnp_v1.1.2/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ts-pnp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ts-pnp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ts-pnp/index' {
  declare module.exports: $Exports<'ts-pnp'>;
}
declare module 'ts-pnp/index.js' {
  declare module.exports: $Exports<'ts-pnp'>;
}
